require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const Product = require("./models/Product");
const User = require("./models/User");

const products = [
  // FRUITS
  { id:"f1",  slug:"banana-robusta",          name:"Banana - Robusta",                    brand:"Fresho", weight:"1 kg",                     price:56,  mrp:78,  rating:4.3, ratingCount:12453, image:"/fresh-yellow-bananas-bunch-on-white-background.jpg", deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Banana",       description:"Naturally ripened Robusta bananas. Rich in potassium.", inStock:true },
  { id:"f2",  slug:"apple-royal-gala",         name:"Apple - Royal Gala, Regular",         brand:"Fresho", weight:"4 pcs (approx. 600-800g)", price:199, mrp:240, rating:4.2, ratingCount:8921,  image:"/red-royal-gala-apples-fresh.jpg",                    deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Apple",        description:"Crisp Royal Gala apples. Perfect for snacking.", inStock:true },
  { id:"f3",  slug:"pomegranate",              name:"Pomegranate",                         brand:"Fresho", weight:"500 g",                     price:119, mrp:160, rating:4.1, ratingCount:5421,  image:"/fresh-pomegranate-fruit-cut-open.jpg",               deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Pomegranate",  description:"Ruby-red pomegranates loaded with antioxidants.", inStock:true },
  { id:"f4",  slug:"orange-imported",          name:"Orange - Imported",                   brand:"Fresho", weight:"1 kg",                     price:189, mrp:220, rating:4.4, ratingCount:3210,  image:"/fresh-juicy-oranges-citrus.jpg",                     deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Orange",       description:"Imported juicy oranges packed with vitamin C.", inStock:true },
  { id:"f5",  slug:"watermelon-kiran",         name:"Watermelon - Kiran",                  brand:"Fresho", weight:"1 pc (approx. 2-3 kg)",    price:89,  mrp:120, rating:4.0, ratingCount:2876,  image:"/whole-and-sliced-watermelon-red.jpg",                deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Watermelon",   description:"Sweet hydrating Kiran watermelon.", inStock:true },
  { id:"f6",  slug:"grapes-black-seedless",    name:"Grapes - Black, Seedless",            brand:"Fresho", weight:"500 g",                    price:99,  mrp:130, rating:4.2, ratingCount:4532,  image:"/black-seedless-grapes-bunch-fresh.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Grapes",       description:"Plump seedless black grapes with sweet-tangy flavour.", inStock:true },
  { id:"f7",  slug:"mango-alphonso",           name:"Mango - Alphonso, Premium",           brand:"Fresho", weight:"1 kg",                     price:449, mrp:599, rating:4.6, ratingCount:15678, image:"/alphonso-mango-yellow-ripe-premium.jpg",             deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Mango",        description:"The king of mangoes — premium Alphonso.", inStock:true },
  { id:"f8",  slug:"papaya-semi-ripe",         name:"Papaya - Semi Ripe",                  brand:"Fresho", weight:"1 pc (approx. 800g-1.2kg)",price:65,  mrp:90,  rating:3.9, ratingCount:1843,  image:"/papaya-fruit-orange-ripe.jpg",                       deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Papaya",       description:"Semi-ripe papaya ideal for digestion.", inStock:true },
  { id:"f9",  slug:"kiwi-green",               name:"Kiwi - Green",                        brand:"Fresho", weight:"3 pcs (approx. 240-270g)", price:149, mrp:210, rating:4.3, ratingCount:3987,  image:"/green-kiwi-fruit-sliced-fresh.jpg",                  deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Kiwi",         description:"Tangy sweet imported green kiwi loaded with vitamin C.", inStock:true },
  { id:"f10", slug:"strawberry",               name:"Strawberry",                          brand:"Fresho", weight:"200 g",                    price:99,  mrp:140, rating:4.0, ratingCount:2134,  image:"/red-fresh-strawberries-in-basket.jpg",               deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Berry",        description:"Bright red strawberries perfect for desserts.", inStock:true },
  { id:"f11", slug:"pineapple",                name:"Pineapple",                           brand:"Fresho", weight:"1 pc (approx. 1.5-2 kg)", price:79,  mrp:110, rating:4.1, ratingCount:2876,  image:"/whole-pineapple-tropical-fruit.jpg",                 deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Pineapple",    description:"Tropical tangy-sweet pineapple.", inStock:true },
  { id:"f12", slug:"guava-red",                name:"Guava - Red",                         brand:"Fresho", weight:"500 g",                    price:49,  mrp:70,  rating:3.8, ratingCount:987,   image:"/red-guava-fruit-sliced-pink-flesh.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Guava",        description:"Pink-fleshed red guava naturally sweet and high in fibre.", inStock:true },
  { id:"f13", slug:"dragon-fruit-white",       name:"Dragon Fruit - White",                brand:"Fresho", weight:"1 pc (approx. 300-400g)", price:89,  mrp:130, rating:4.2, ratingCount:1432,  image:"/dragon-fruit-pink-exotic-tropical.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Exotic",       description:"Mildly sweet exotic dragon fruit rich in antioxidants.", inStock:true },
  { id:"f14", slug:"avocado-imported",         name:"Avocado - Imported",                  brand:"Fresho", weight:"2 pcs (approx. 380-460g)", price:299, mrp:399, rating:4.4, ratingCount:2543,  image:"/avocado-green-halved-with-pit.jpg",                  deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Exotic",       description:"Buttery imported avocados perfect for toast and salads.", inStock:true },
  { id:"f15", slug:"blueberry",                name:"Blueberry",                           brand:"Fresho", weight:"125 g",                    price:199, mrp:280, rating:4.5, ratingCount:1876,  image:"/fresh-blueberries-in-bowl.jpg",                      deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Berry",        description:"Plump antioxidant-rich blueberries.", inStock:true },
  { id:"f16", slug:"sweet-lime-mosambi",       name:"Sweet Lime / Mosambi",                brand:"Fresho", weight:"1 kg",                     price:79,  mrp:100, rating:4.0, ratingCount:3210,  image:"/sweet-lime-mosambi-green-citrus.jpg",                deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Citrus",       description:"Refreshing mosambi naturally rich in vitamin C.", inStock:true },
  { id:"f17", slug:"mango-kesar",              name:"Mango - Kesar",                       brand:"Fresho", weight:"1 kg (5-6 pcs)",           price:349, mrp:450, rating:4.6, ratingCount:11200, image:"/colorful-assortment-fresh-fruits-banner.jpg",        deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Mango",        description:"Aromatic Kesar mangoes from Gujarat.", inStock:true },
  { id:"f18", slug:"pear-williams",            name:"Pear - Williams, Fresh",              brand:"Fresho", weight:"4 pcs (approx. 500g)",     price:149, mrp:190, rating:4.2, ratingCount:5430,  image:"/red-guava-fruit-sliced-pink-flesh.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Pear",         description:"Soft and sweet Williams pears with buttery texture.", inStock:true },
  { id:"f19", slug:"cherry-fresh",             name:"Cherry - Fresh, Red",                 brand:"Fresho", weight:"250 g",                    price:299, mrp:380, rating:4.5, ratingCount:3210,  image:"/fresh-blueberries-in-bowl.jpg",                      deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Cherry",       description:"Plump sweet-tart red cherries rich in antioxidants.", inStock:true },
  { id:"f20", slug:"coconut-fresh",            name:"Coconut - Fresh, Whole",              brand:"Fresho", weight:"1 pc (approx. 400-500g)", price:45,  mrp:60,  rating:4.3, ratingCount:18900, image:"/whole-pineapple-tropical-fruit.jpg",                 deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Coconut",      description:"Fresh whole coconut with tender flesh and coconut water.", inStock:true },
  { id:"f21", slug:"fig-fresh",                name:"Fig - Fresh, Green",                  brand:"Fresho", weight:"250 g (6-8 pcs)",          price:199, mrp:250, rating:4.4, ratingCount:2870,  image:"/dragon-fruit-pink-exotic-tropical.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Fig",          description:"Fresh green figs with honey-sweet flavour.", inStock:true },
  { id:"f22", slug:"peach-fresh",              name:"Peach - Fresh",                       brand:"Fresho", weight:"4 pcs (approx. 400g)",     price:179, mrp:220, rating:4.3, ratingCount:4120,  image:"/fresh-pomegranate-fruit-cut-open.jpg",               deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Peach",        description:"Juicy fragrant peaches with soft velvety skin.", inStock:true },
  { id:"f23", slug:"plum-fresh",               name:"Plum - Fresh, Red",                   brand:"Fresho", weight:"500 g (6-8 pcs)",          price:149, mrp:190, rating:4.2, ratingCount:3780,  image:"/black-seedless-grapes-bunch-fresh.jpg",              deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Plum",         description:"Sweet and tangy red plums.", inStock:true },
  { id:"f24", slug:"litchi-fresh",             name:"Litchi - Fresh",                      brand:"Fresho", weight:"500 g",                    price:129, mrp:160, rating:4.5, ratingCount:8760,  image:"/fresh-juicy-oranges-citrus.jpg",                     deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Litchi",       description:"Juicy litchis packed with Vitamin C.", inStock:true },
  { id:"f25", slug:"grapes-green-seedless",    name:"Grapes - Green Seedless",             brand:"Fresho", weight:"500 g",                    price:99,  mrp:125, rating:4.4, ratingCount:11230, image:"/whole-and-sliced-watermelon-red.jpg",                deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Grapes",       description:"Crisp sweet seedless green grapes.", inStock:true },
  { id:"f26", slug:"sapota-chikoo",            name:"Sapota (Chikoo) - Fresh",             brand:"Fresho", weight:"500 g (4-6 pcs)",          price:79,  mrp:100, rating:4.2, ratingCount:6540,  image:"/papaya-fruit-orange-ripe.jpg",                       deliveryTime:"Tomorrow 7AM", type:"fruit",     category:"Sapota",       description:"Sweet malty chikoo rich in iron and calcium.", inStock:true },
  // VEGETABLES
  { id:"v1",  slug:"tomato-local",             name:"Tomato - Local",                      brand:"Fresho", weight:"1 kg",                     price:32,  mrp:50,  rating:4.1, ratingCount:9821,  image:"/red-ripe-tomatoes-fresh.jpg",                        deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Tomato",       description:"Juicy red tomatoes for curries, salads and sauces.", inStock:true },
  { id:"v2",  slug:"onion",                    name:"Onion",                               brand:"Fresho", weight:"1 kg",                     price:45,  mrp:60,  rating:4.0, ratingCount:8421,  image:"/fresh-red-onions-on-white.jpg",                      deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Onion",        description:"Premium red onions. Daily kitchen staple.", inStock:true },
  { id:"v3",  slug:"potato",                   name:"Potato",                              brand:"Fresho", weight:"1 kg",                     price:38,  mrp:50,  rating:4.2, ratingCount:11234, image:"/fresh-potatoes-brown-skin.jpg",                      deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Potato",       description:"Fresh potatoes great for fries, curries and roasts.", inStock:true },
  { id:"v4",  slug:"carrot-orange",            name:"Carrot - Orange",                     brand:"Fresho", weight:"500 g",                    price:39,  mrp:55,  rating:4.3, ratingCount:4532,  image:"/fresh-orange-carrots-bunch.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Carrot",       description:"Crunchy orange carrots rich in beta-carotene.", inStock:true },
  { id:"v5",  slug:"cucumber-english",         name:"Cucumber - English",                  brand:"Fresho", weight:"500 g",                    price:29,  mrp:40,  rating:4.1, ratingCount:3210,  image:"/fresh-green-cucumber-on-white.jpg",                  deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Cucumber",     description:"Long crisp English cucumbers perfect for salads.", inStock:true },
  { id:"v6",  slug:"cabbage",                  name:"Cabbage",                             brand:"Fresho", weight:"1 pc (approx. 600-900g)", price:35,  mrp:50,  rating:4.0, ratingCount:1876,  image:"/fresh-green-cabbage-head.jpg",                       deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Cabbage",      description:"Crisp green cabbage for stir-fries, soups and slaws.", inStock:true },
  { id:"v7",  slug:"cauliflower",              name:"Cauliflower",                         brand:"Fresho", weight:"1 pc (approx. 500-800g)", price:42,  mrp:60,  rating:4.0, ratingCount:1543,  image:"/fresh-white-cauliflower-head.jpg",                   deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Cauliflower",  description:"Fresh white cauliflower with tight snowy florets.", inStock:true },
  { id:"v8",  slug:"broccoli",                 name:"Broccoli",                            brand:"Fresho", weight:"250 g",                    price:89,  mrp:120, rating:4.3, ratingCount:2134,  image:"/fresh-green-broccoli-florets.jpg",                   deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Broccoli",     description:"Tender green broccoli florets packed with nutrients.", inStock:true },
  { id:"v9",  slug:"capsicum-green",           name:"Capsicum - Green",                    brand:"Fresho", weight:"500 g",                    price:49,  mrp:70,  rating:4.1, ratingCount:2876,  image:"/fresh-green-bell-peppers-capsicum.jpg",              deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Capsicum",     description:"Crunchy green bell peppers.", inStock:true },
  { id:"v10", slug:"spinach-palak",            name:"Spinach (Palak)",                     brand:"Fresho", weight:"250 g",                    price:19,  mrp:30,  rating:4.2, ratingCount:3987,  image:"/fresh-green-spinach-leaves-palak.jpg",               deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Leafy",        description:"Tender iron-rich spinach leaves.", inStock:true },
  { id:"v11", slug:"beans-french",             name:"Beans - French",                      brand:"Fresho", weight:"250 g",                    price:25,  mrp:40,  rating:4.0, ratingCount:1432,  image:"/fresh-green-french-beans.jpg",                       deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Beans",        description:"Crisp tender French beans.", inStock:true },
  { id:"v12", slug:"brinjal-purple",           name:"Brinjal - Purple, Long",              brand:"Fresho", weight:"500 g",                    price:39,  mrp:55,  rating:3.9, ratingCount:987,   image:"/long-purple-brinjal-eggplant-fresh.jpg",             deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Brinjal",      description:"Glossy purple brinjals for bharta and curries.", inStock:true },
  { id:"v13", slug:"lemon",                    name:"Lemon",                               brand:"Fresho", weight:"250 g",                    price:22,  mrp:35,  rating:4.2, ratingCount:5421,  image:"/fresh-yellow-lemons-citrus.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Citrus",       description:"Tangy fresh lemons for juice and marinades.", inStock:true },
  { id:"v14", slug:"ginger",                   name:"Ginger",                              brand:"Fresho", weight:"250 g",                    price:35,  mrp:50,  rating:4.0, ratingCount:3210,  image:"/fresh-ginger-root-on-white.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Roots",        description:"Aromatic fresh ginger root for curries and teas.", inStock:true },
  { id:"v15", slug:"garlic",                   name:"Garlic",                              brand:"Fresho", weight:"200 g",                    price:49,  mrp:70,  rating:4.1, ratingCount:2543,  image:"/fresh-garlic-bulbs-on-white.jpg",                    deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Roots",        description:"Plump aromatic garlic bulbs.", inStock:true },
  { id:"v16", slug:"mushroom-button",          name:"Mushroom - Button",                   brand:"Fresho", weight:"200 g",                    price:65,  mrp:95,  rating:4.3, ratingCount:1876,  image:"/fresh-white-button-mushrooms.jpg",                   deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Mushroom",     description:"Fresh white button mushrooms with mild earthy flavour.", inStock:true },
  { id:"v17", slug:"peas-green-fresh",         name:"Green Peas - Fresh",                  brand:"Fresho", weight:"500 g",                    price:55,  mrp:75,  rating:4.3, ratingCount:9870,  image:"/fresh-green-broccoli-florets.jpg",                   deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Peas",         description:"Tender fresh green peas perfect for pulao and soups.", inStock:true },
  { id:"v18", slug:"beetroot-fresh",           name:"Beetroot - Fresh",                    brand:"Fresho", weight:"500 g (3-4 pcs)",          price:45,  mrp:60,  rating:4.2, ratingCount:7650,  image:"/fresh-pomegranate-fruit-cut-open.jpg",               deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Beetroot",     description:"Deep red beetroots rich in iron and folate.", inStock:true },
  { id:"v19", slug:"sweet-potato-fresh",       name:"Sweet Potato - Fresh",                brand:"Fresho", weight:"500 g",                    price:49,  mrp:65,  rating:4.1, ratingCount:6230,  image:"/fresh-potatoes-brown-skin.jpg",                      deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Sweet Potato", description:"Naturally sweet potatoes high in beta-carotene.", inStock:true },
  { id:"v20", slug:"lady-finger-okra",         name:"Lady Finger (Okra) - Fresh",          brand:"Fresho", weight:"250 g",                    price:35,  mrp:50,  rating:4.0, ratingCount:8900,  image:"/fresh-green-cucumber-on-white.jpg",                  deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Lady Finger",  description:"Fresh tender okra perfect for bhindi masala.", inStock:true },
  { id:"v21", slug:"radish-white-fresh",       name:"Radish - White, Fresh",               brand:"Fresho", weight:"500 g (2-3 pcs)",          price:29,  mrp:40,  rating:4.0, ratingCount:7120,  image:"/fresh-orange-carrots-bunch.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Radish",       description:"Crisp white radish great for mooli paratha.", inStock:true },
  { id:"v22", slug:"capsicum-red-fresh",       name:"Capsicum - Red, Fresh",               brand:"Fresho", weight:"250 g (2 pcs)",            price:69,  mrp:90,  rating:4.3, ratingCount:5430,  image:"/red-ripe-tomatoes-fresh.jpg",                        deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Capsicum",     description:"Sweet vibrant red bell peppers.", inStock:true },
  { id:"v23", slug:"capsicum-yellow-fresh",    name:"Capsicum - Yellow, Fresh",            brand:"Fresho", weight:"250 g (2 pcs)",            price:69,  mrp:90,  rating:4.2, ratingCount:4320,  image:"/fresh-yellow-lemons-citrus.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Capsicum",     description:"Mildly sweet yellow bell peppers.", inStock:true },
  { id:"v24", slug:"raw-banana-fresh",         name:"Raw Banana - Fresh",                  brand:"Fresho", weight:"4 pcs (approx. 500g)",     price:39,  mrp:55,  rating:4.1, ratingCount:6780,  image:"/fresh-yellow-bananas-bunch-on-white-background.jpg", deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Raw Banana",   description:"Firm raw bananas ideal for Kerala curries.", inStock:true },
  { id:"v25", slug:"raw-mango-fresh",          name:"Raw Mango - Fresh",                   brand:"Fresho", weight:"500 g (2-3 pcs)",          price:59,  mrp:80,  rating:4.2, ratingCount:9870,  image:"/fresh-juicy-oranges-citrus.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Raw Mango",    description:"Tangy raw mangoes perfect for pickles and chutneys.", inStock:true },
  { id:"v26", slug:"drumstick-fresh",          name:"Drumstick (Moringa) - Fresh",         brand:"Fresho", weight:"250 g (4-5 pcs)",          price:35,  mrp:50,  rating:4.1, ratingCount:7650,  image:"/long-purple-brinjal-eggplant-fresh.jpg",             deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Drumstick",    description:"Fresh moringa drumsticks essential for sambar.", inStock:true },
  { id:"v27", slug:"curry-leaves-fresh",       name:"Curry Leaves - Fresh",                brand:"Fresho", weight:"50 g (1 bunch)",           price:15,  mrp:25,  rating:4.4, ratingCount:14320, image:"/fresh-green-cabbage-head.jpg",                       deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Herbs",        description:"Fragrant fresh curry leaves for South Indian cooking.", inStock:true },
  { id:"v28", slug:"coriander-fresh",          name:"Coriander - Fresh",                   brand:"Fresho", weight:"100 g (1 bunch)",          price:15,  mrp:25,  rating:4.3, ratingCount:19870, image:"/avocado-green-halved-with-pit.jpg",                  deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Herbs",        description:"Fresh aromatic coriander leaves.", inStock:true },
  { id:"v29", slug:"mint-leaves-fresh",        name:"Mint Leaves - Fresh",                 brand:"Fresho", weight:"50 g (1 bunch)",           price:15,  mrp:25,  rating:4.3, ratingCount:12430, image:"/fresh-green-spinach-leaves-palak.jpg",               deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Herbs",        description:"Cool refreshing mint leaves for chutneys and biryanis.", inStock:true },
  { id:"v30", slug:"pumpkin-yellow-fresh",     name:"Pumpkin - Yellow, Fresh",             brand:"Fresho", weight:"500 g",                    price:35,  mrp:50,  rating:4.0, ratingCount:6540,  image:"/fresh-ginger-root-on-white.jpg",                     deliveryTime:"Tomorrow 7AM", type:"vegetable", category:"Pumpkin",      description:"Sweet yellow pumpkin for sabzi, soups and halwa.", inStock:true },
]

const seed = async () => {
  await connectDB()
  await Product.deleteMany({})
  await User.deleteMany({})
  await Product.insertMany(products)
  console.log(`✅ Seeded ${products.length} products`)
  await User.create({ name:"Admin", email:"admin@freshbasket.com", password:"admin123", role:"admin" })
  console.log("✅ Created admin user: admin@freshbasket.com / admin123")
  await User.create({ name:"Test User", email:"user@freshbasket.com", password:"user123", role:"user" })
  console.log("✅ Created test user: user@freshbasket.com / user123")
  mongoose.disconnect()
  console.log("🎉 Seeding complete!")
}

seed().catch(err => { console.error(err); process.exit(1) })
